# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'avalanchestudio.avalanchecrm::lang.models.subscription.label'

# Model Form Field configuration
form: $/avalanchestudio/avalanchecrm/models/subscription/fields.yaml

# Model Class name
modelClass: AvalancheStudio\AvalancheCRM\Models\Subscription

# Default redirect location
defaultRedirect: avalanchestudio/avalanchecrm/subscriptions

# Create page
create:
    title: backend::lang.form.create_title
    redirect: avalanchestudio/avalanchecrm/subscriptions/update/:id
    redirectClose: avalanchestudio/avalanchecrm/subscriptions

# Update page
update:
    title: backend::lang.form.update_title
    redirect: avalanchestudio/avalanchecrm/subscriptions
    redirectClose: avalanchestudio/avalanchecrm/subscriptions

# Preview page
preview:
    title: backend::lang.form.preview_title
